#
# A gitlab-ci file to build web assets and deployment
#

deploy:
  image:
    name: node:12-alpine
    entrypoint: ['']
  only:
    - main
  script:
    - apk add --no-cache curl
    - ./bin/deploy
