#
# A gitlab-ci file to build web assets and deployment
#

deploy:
  image:
    name: node:12-alpine
    entrypoint: ['']
  tags:
    - docker
  only:
    - master
  script:
    - apk add --no-cache curl
    - NODE_ENV=production npm ci
    - npm run build
    - tar -zcvf archive.tar.gz -C dist .
    - 'curl --silent --header "Authorization: Bearer $DEPLOY_KEY" --form archive=@archive.tar.gz $DEPLOY_URL'
